import 'package:foap/helper/imports/common_import.dart';
import '../../model/country_model.dart';

showWKCurrencyPicker({
  required BuildContext context,
  required ValueChanged<Country> onSelect,
}) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (context) => FractionallySizedBox(
        heightFactor: 0.8,
        child: CurrencyPicker(
          onSelect: onSelect,
        ).topRounded(20)),
  );
}

class CurrencyPicker extends StatefulWidget {
  final ValueChanged<Country> onSelect;

  const CurrencyPicker({
    super.key,
    required this.onSelect,
  });

  @override
  State<CurrencyPicker> createState() => _CurrencyPickerState();
}

class _CurrencyPickerState extends State<CurrencyPicker> {
  List<Country> countries = [
    Country(
        name: 'Angola',
        code: 'AO',
        dialCode: '+244',
        currency: 'Angolan Kwanza',
        currencySymbol: 'Kz',
        flag: '🇦🇴'),
    Country(
        name: 'Antigua and Barbuda',
        code: 'AG',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇦🇬'),
    Country(
        name: 'Argentina',
        code: 'AR',
        dialCode: '+54',
        currency: 'Argentine Peso',
        currencySymbol: '\$',
        flag: '🇦🇷'),
    Country(
        name: 'Armenia',
        code: 'AM',
        dialCode: '+374',
        currency: 'Armenian Dram',
        currencySymbol: '֏',
        flag: '🇦🇲'),
    Country(
        name: 'Australia',
        code: 'AU',
        dialCode: '+61',
        currency: 'Australian Dollar',
        currencySymbol: '\$',
        flag: '🇦🇺'),
    Country(
        name: 'Austria',
        code: 'AT',
        dialCode: '+43',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇦🇹'),
    Country(
        name: 'Azerbaijan',
        code: 'AZ',
        dialCode: '+994',
        currency: 'Azerbaijani Manat',
        currencySymbol: '₼',
        flag: '🇦🇿'),
    Country(
        name: 'Bahamas',
        code: 'BS',
        dialCode: '+1',
        currency: 'Bahamian Dollar',
        currencySymbol: '\$',
        flag: '🇧🇸'),
    Country(
        name: 'Bahrain',
        code: 'BH',
        dialCode: '+973',
        currency: 'Bahraini Dinar',
        currencySymbol: '.د.ب',
        flag: '🇧🇭'),
    Country(
        name: 'Bangladesh',
        code: 'BD',
        dialCode: '+880',
        currency: 'Bangladeshi Taka',
        currencySymbol: '৳',
        flag: '🇧🇩'),
    Country(
        name: 'Barbados',
        code: 'BB',
        dialCode: '+1',
        currency: 'Barbadian Dollar',
        currencySymbol: '\$',
        flag: '🇧🇧'),
    Country(
        name: 'Belarus',
        code: 'BY',
        dialCode: '+375',
        currency: 'Belarusian Ruble',
        currencySymbol: 'Br',
        flag: '🇧🇾'),
    Country(
        name: 'Belgium',
        code: 'BE',
        dialCode: '+32',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇧🇪'),
    Country(
        name: 'Belize',
        code: 'BZ',
        dialCode: '+501',
        currency: 'Belize Dollar',
        currencySymbol: '\$',
        flag: '🇧🇿'),
    Country(
        name: 'Benin',
        code: 'BJ',
        dialCode: '+229',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇧🇯'),
    Country(
        name: 'Bhutan',
        code: 'BT',
        dialCode: '+975',
        currency: 'Bhutanese Ngultrum',
        currencySymbol: 'Nu.',
        flag: '🇧🇹'),
    Country(
        name: 'Bolivia',
        code: 'BO',
        dialCode: '+591',
        currency: 'Bolivian Boliviano',
        currencySymbol: 'Bs.',
        flag: '🇧🇴'),
    Country(
        name: 'Bosnia and Herzegovina',
        code: 'BA',
        dialCode: '+387',
        currency: 'Bosnia and Herzegovina Convertible Mark',
        currencySymbol: 'KM',
        flag: '🇧🇦'),
    Country(
        name: 'Botswana',
        code: 'BW',
        dialCode: '+267',
        currency: 'Botswana Pula',
        currencySymbol: 'P',
        flag: '🇧🇼'),
    Country(
        name: 'Brazil',
        code: 'BR',
        dialCode: '+55',
        currency: 'Brazilian Real',
        currencySymbol: 'R\$',
        flag: '🇧🇷'),
    Country(
        name: 'Brunei Darussalam',
        code: 'BN',
        dialCode: '+673',
        currency: 'Brunei Dollar',
        currencySymbol: '\$',
        flag: '🇧🇳'),
    Country(
        name: 'Bulgaria',
        code: 'BG',
        dialCode: '+359',
        currency: 'Bulgarian Lev',
        currencySymbol: 'лв',
        flag: '🇧🇬'),
    Country(
        name: 'Burkina Faso',
        code: 'BF',
        dialCode: '+226',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇧🇫'),
    Country(
        name: 'Burundi',
        code: 'BI',
        dialCode: '+257',
        currency: 'Burundian Franc',
        currencySymbol: 'Fr',
        flag: '🇧🇮'),
    Country(
        name: 'Cabo Verde',
        code: 'CV',
        dialCode: '+238',
        currency: 'Cape Verdean Escudo',
        currencySymbol: '\$',
        flag: '🇨🇻'),
    Country(
        name: 'Cambodia',
        code: 'KH',
        dialCode: '+855',
        currency: 'Cambodian Riel',
        currencySymbol: '៛',
        flag: '🇰🇭'),
    Country(
        name: 'Cameroon',
        code: 'CM',
        dialCode: '+237',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇨🇲'),
    Country(
        name: 'Canada',
        code: 'CA',
        dialCode: '+1',
        currency: 'Canadian Dollar',
        currencySymbol: '\$',
        flag: '🇨🇦'),
    Country(
        name: 'Central African Republic',
        code: 'CF',
        dialCode: '+236',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇨🇫'),
    Country(
        name: 'Chad',
        code: 'TD',
        dialCode: '+235',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇹🇩'),
    Country(
        name: 'Chile',
        code: 'CL',
        dialCode: '+56',
        currency: 'Chilean Peso',
        currencySymbol: '\$',
        flag: '🇨🇱'),
    Country(
        name: 'China',
        code: 'CN',
        dialCode: '+86',
        currency: 'Renminbi (Chinese) yuan',
        currencySymbol: '¥',
        flag: '🇨🇳'),
    Country(
        name: 'Colombia',
        code: 'CO',
        dialCode: '+57',
        currency: 'Colombian Peso',
        currencySymbol: '\$',
        flag: '🇨🇴'),
    Country(
        name: 'Comoros',
        code: 'KM',
        dialCode: '+269',
        currency: 'Comorian Franc',
        currencySymbol: 'Fr',
        flag: '🇰🇲'),
    Country(
        name: 'Congo',
        code: 'CG',
        dialCode: '+242',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇨🇬'),
    Country(
        name: 'Congo, Democratic Republic of the',
        code: 'CD',
        dialCode: '+243',
        currency: 'Congolese Franc',
        currencySymbol: 'Fr',
        flag: '🇨🇩'),
    Country(
        name: 'Costa Rica',
        code: 'CR',
        dialCode: '+506',
        currency: 'Costa Rican Colón',
        currencySymbol: '₡',
        flag: '🇨🇷'),
    Country(
        name: "Côte d'Ivoire",
        code: 'CI',
        dialCode: '+225',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇨🇮'),
    Country(
        name: 'Croatia',
        code: 'HR',
        dialCode: '+385',
        currency: 'Croatian Kuna',
        currencySymbol: 'kn',
        flag: '🇭🇷'),
    Country(
        name: 'Cuba',
        code: 'CU',
        dialCode: '+53',
        currency: 'Cuban Peso',
        currencySymbol: '₱',
        flag: '🇨🇺'),
    Country(
        name: 'Cyprus',
        code: 'CY',
        dialCode: '+357',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇨🇾'),
    Country(
        name: 'Czech Republic',
        code: 'CZ',
        dialCode: '+420',
        currency: 'Czech Koruna',
        currencySymbol: 'Kč',
        flag: '🇨🇿'),
    Country(
        name: 'Denmark',
        code: 'DK',
        dialCode: '+45',
        currency: 'Danish Krone',
        currencySymbol: 'kr',
        flag: '🇩🇰'),
    Country(
        name: 'Djibouti',
        code: 'DJ',
        dialCode: '+253',
        currency: 'Djiboutian Franc',
        currencySymbol: 'Fr',
        flag: '🇩🇯'),
    Country(
        name: 'Dominica',
        code: 'DM',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇩🇲'),
    Country(
        name: 'Dominican Republic',
        code: 'DO',
        dialCode: '+1',
        currency: 'Dominican Peso',
        currencySymbol: '\$',
        flag: '🇩🇴'),
    Country(
        name: 'Ecuador',
        code: 'EC',
        dialCode: '+593',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇪🇨'),
    Country(
        name: 'Egypt',
        code: 'EG',
        dialCode: '+20',
        currency: 'Egyptian Pound',
        currencySymbol: 'E£',
        flag: '🇪🇬'),
    Country(
        name: 'El Salvador',
        code: 'SV',
        dialCode: '+503',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇸🇻'),
    Country(
        name: 'Equatorial Guinea',
        code: 'GQ',
        dialCode: '+240',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇬🇶'),
    Country(
        name: 'Eritrea',
        code: 'ER',
        dialCode: '+291',
        currency: 'Eritrean Nakfa',
        currencySymbol: 'Nfk',
        flag: '🇪🇷'),
    Country(
        name: 'Estonia',
        code: 'EE',
        dialCode: '+372',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇪🇪'),
    Country(
        name: 'Eswatini',
        code: 'SZ',
        dialCode: '+268',
        currency: 'Swazi Lilangeni',
        currencySymbol: 'L',
        flag: '🇸🇿'),
    Country(
        name: 'Ethiopia',
        code: 'ET',
        dialCode: '+251',
        currency: 'Ethiopian Birr',
        currencySymbol: 'Br',
        flag: '🇪🇹'),
    Country(
        name: 'Fiji',
        code: 'FJ',
        dialCode: '+679',
        currency: 'Fijian Dollar',
        currencySymbol: '\$',
        flag: '🇫🇯'),
    Country(
        name: 'Finland',
        code: 'FI',
        dialCode: '+358',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇫🇮'),
    Country(
        name: 'France',
        code: 'FR',
        dialCode: '+33',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇫🇷'),
    Country(
        name: 'Gabon',
        code: 'GA',
        dialCode: '+241',
        currency: 'Central African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇬🇦'),
    Country(
        name: 'Gambia',
        code: 'GM',
        dialCode: '+220',
        currency: 'Gambian Dalasi',
        currencySymbol: 'D',
        flag: '🇬🇲'),
    Country(
        name: 'Georgia',
        code: 'GE',
        dialCode: '+995',
        currency: 'Georgian Lari',
        currencySymbol: '₾',
        flag: '🇬🇪'),
    Country(
        name: 'Germany',
        code: 'DE',
        dialCode: '+49',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇩🇪'),
    Country(
        name: 'Ghana',
        code: 'GH',
        dialCode: '+233',
        currency: 'Ghanaian Cedi',
        currencySymbol: '₵',
        flag: '🇬🇭'),
    Country(
        name: 'Greece',
        code: 'GR',
        dialCode: '+30',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇬🇷'),
    Country(
        name: 'Grenada',
        code: 'GD',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇬🇩'),
    Country(
        name: 'Guatemala',
        code: 'GT',
        dialCode: '+502',
        currency: 'Guatemalan Quetzal',
        currencySymbol: 'Q',
        flag: '🇬🇹'),
    Country(
        name: 'Guinea',
        code: 'GN',
        dialCode: '+224',
        currency: 'Guinean Franc',
        currencySymbol: 'Fr',
        flag: '🇬🇳'),
    Country(
        name: 'Guinea-Bissau',
        code: 'GW',
        dialCode: '+245',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇬🇼'),
    Country(
        name: 'Guyana',
        code: 'GY',
        dialCode: '+592',
        currency: 'Guyanese Dollar',
        currencySymbol: '\$',
        flag: '🇬🇾'),
    Country(
        name: 'Haiti',
        code: 'HT',
        dialCode: '+509',
        currency: 'Haitian Gourde',
        currencySymbol: 'G',
        flag: '🇭🇹'),
    Country(
        name: 'Holy See',
        code: 'VA',
        dialCode: '+379',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇻🇦'),
    Country(
        name: 'Honduras',
        code: 'HN',
        dialCode: '+504',
        currency: 'Honduran Lempira',
        currencySymbol: 'L',
        flag: '🇭🇳'),
    Country(
        name: 'Hong Kong',
        code: 'HK',
        dialCode: '+852',
        currency: 'Hong Kong Dollar',
        currencySymbol: '\$',
        flag: '🇭🇰'),
    Country(
        name: 'Hungary',
        code: 'HU',
        dialCode: '+36',
        currency: 'Hungarian Forint',
        currencySymbol: 'Ft',
        flag: '🇭🇺'),
    Country(
        name: 'Iceland',
        code: 'IS',
        dialCode: '+354',
        currency: 'Icelandic Króna',
        currencySymbol: 'kr',
        flag: '🇮🇸'),
    Country(
        name: 'India',
        code: 'IN',
        dialCode: '+91',
        currency: 'Indian Rupee',
        currencySymbol: '₹',
        flag: '🇮🇳'),
    Country(
        name: 'Indonesia',
        code: 'ID',
        dialCode: '+62',
        currency: 'Indonesian Rupiah',
        currencySymbol: 'Rp',
        flag: '🇮🇩'),
    Country(
        name: 'Iran',
        code: 'IR',
        dialCode: '+98',
        currency: 'Iranian Rial',
        currencySymbol: '﷼',
        flag: '🇮🇷'),
    Country(
        name: 'Iraq',
        code: 'IQ',
        dialCode: '+964',
        currency: 'Iraqi Dinar',
        currencySymbol: 'ع.د',
        flag: '🇮🇶'),
    Country(
        name: 'Ireland',
        code: 'IE',
        dialCode: '+353',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇮🇪'),
    Country(
        name: 'Israel',
        code: 'IL',
        dialCode: '+972',
        currency: 'Israeli New Shekel',
        currencySymbol: '₪',
        flag: '🇮🇱'),
    Country(
        name: 'Italy',
        code: 'IT',
        dialCode: '+39',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇮🇹'),
    Country(
        name: 'Jamaica',
        code: 'JM',
        dialCode: '+1',
        currency: 'Jamaican Dollar',
        currencySymbol: '\$',
        flag: '🇯🇲'),
    Country(
        name: 'Japan',
        code: 'JP',
        dialCode: '+81',
        currency: 'Japanese Yen',
        currencySymbol: '¥',
        flag: '🇯🇵'),
    Country(
        name: 'Jordan',
        code: 'JO',
        dialCode: '+962',
        currency: 'Jordanian Dinar',
        currencySymbol: 'د.ا',
        flag: '🇯🇴'),
    Country(
        name: 'Kazakhstan',
        code: 'KZ',
        dialCode: '+7',
        currency: 'Kazakhstani Tenge',
        currencySymbol: '₸',
        flag: '🇰🇿'),
    Country(
        name: 'Kenya',
        code: 'KE',
        dialCode: '+254',
        currency: 'Kenyan Shilling',
        currencySymbol: 'Sh',
        flag: '🇰🇪'),
    Country(
        name: 'Kiribati',
        code: 'KI',
        dialCode: '+686',
        currency: 'Australian Dollar',
        currencySymbol: '\$',
        flag: '🇰🇮'),
    Country(
        name: 'Korea',
        code: 'KR',
        dialCode: '+82',
        currency: 'South Korean Won',
        currencySymbol: '₩',
        flag: '🇰🇷'),
    Country(
        name: 'Kuwait',
        code: 'KW',
        dialCode: '+965',
        currency: 'Kuwaiti Dinar',
        currencySymbol: 'د.ك',
        flag: '🇰🇼'),
    Country(
        name: 'Kyrgyzstan',
        code: 'KG',
        dialCode: '+996',
        currency: 'Kyrgyzstani Som',
        currencySymbol: 'с',
        flag: '🇰🇬'),
    Country(
        name: "Lao People's Democratic Republic",
        code: 'LA',
        dialCode: '+856',
        currency: 'Lao Kip',
        currencySymbol: '₭',
        flag: '🇱🇦'),
    Country(
        name: 'Latvia',
        code: 'LV',
        dialCode: '+371',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇱🇻'),
    Country(
        name: 'Lebanon',
        code: 'LB',
        dialCode: '+961',
        currency: 'Lebanese Pound',
        currencySymbol: 'ل.ل',
        flag: '🇱🇧'),
    Country(
        name: 'Lesotho',
        code: 'LS',
        dialCode: '+266',
        currency: 'Lesotho Loti',
        currencySymbol: 'L',
        flag: '🇱🇸'),
    Country(
        name: 'Liberia',
        code: 'LR',
        dialCode: '+231',
        currency: 'Liberian Dollar',
        currencySymbol: '\$',
        flag: '🇱🇷'),
    Country(
        name: 'Libya',
        code: 'LY',
        dialCode: '+218',
        currency: 'Libyan Dinar',
        currencySymbol: 'ل.د',
        flag: '🇱🇾'),
    Country(
        name: 'Liechtenstein',
        code: 'LI',
        dialCode: '+423',
        currency: 'Swiss Franc',
        currencySymbol: 'CHF',
        flag: '🇱🇮'),
    Country(
        name: 'Lithuania',
        code: 'LT',
        dialCode: '+370',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇱🇹'),
    Country(
        name: 'Luxembourg',
        code: 'LU',
        dialCode: '+352',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇱🇺'),
    Country(
        name: 'Madagascar',
        code: 'MG',
        dialCode: '+261',
        currency: 'Malagasy Ariary',
        currencySymbol: 'Ar',
        flag: '🇲🇬'),
    Country(
        name: 'Malawi',
        code: 'MW',
        dialCode: '+265',
        currency: 'Malawian Kwacha',
        currencySymbol: 'MK',
        flag: '🇲🇼'),
    Country(
        name: 'Malaysia',
        code: 'MY',
        dialCode: '+60',
        currency: 'Malaysian Ringgit',
        currencySymbol: 'RM',
        flag: '🇲🇾'),
    Country(
        name: 'Maldives',
        code: 'MV',
        dialCode: '+960',
        currency: 'Maldivian Rufiyaa',
        currencySymbol: 'ރ.',
        flag: '🇲🇻'),
    Country(
        name: 'Mali',
        code: 'ML',
        dialCode: '+223',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇲🇱'),
    Country(
        name: 'Malta',
        code: 'MT',
        dialCode: '+356',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇲🇹'),
    Country(
        name: 'Marshall Islands',
        code: 'MH',
        dialCode: '+692',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇲🇭'),
    Country(
        name: 'Mauritania',
        code: 'MR',
        dialCode: '+222',
        currency: 'Mauritanian Ouguiya',
        currencySymbol: 'UM',
        flag: '🇲🇷'),
    Country(
        name: 'Mauritius',
        code: 'MU',
        dialCode: '+230',
        currency: 'Mauritian Rupee',
        currencySymbol: '₨',
        flag: '🇲🇺'),
    Country(
        name: 'Mexico',
        code: 'MX',
        dialCode: '+52',
        currency: 'Mexican Peso',
        currencySymbol: '\$',
        flag: '🇲🇽'),
    Country(
        name: 'Micronesia',
        code: 'FM',
        dialCode: '+691',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇫🇲'),
    Country(
        name: 'Moldova',
        code: 'MD',
        dialCode: '+373',
        currency: 'Moldovan Leu',
        currencySymbol: 'L',
        flag: '🇲🇩'),
    Country(
        name: 'Monaco',
        code: 'MC',
        dialCode: '+377',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇲🇨'),
    Country(
        name: 'Mongolia',
        code: 'MN',
        dialCode: '+976',
        currency: 'Mongolian Tögrög',
        currencySymbol: '₮',
        flag: '🇲🇳'),
    Country(
        name: 'Montenegro',
        code: 'ME',
        dialCode: '+382',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇲🇪'),
    Country(
        name: 'Morocco',
        code: 'MA',
        dialCode: '+212',
        currency: 'Moroccan Dirham',
        currencySymbol: 'د.م.',
        flag: '🇲🇦'),
    Country(
        name: 'Mozambique',
        code: 'MZ',
        dialCode: '+258',
        currency: 'Mozambican Metical',
        currencySymbol: 'MT',
        flag: '🇲🇿'),
    Country(
        name: 'Myanmar',
        code: 'MM',
        dialCode: '+95',
        currency: 'Burmese Kyat',
        currencySymbol: 'Ks',
        flag: '🇲🇲'),
    Country(
        name: 'Namibia',
        code: 'NA',
        dialCode: '+264',
        currency: 'Namibian Dollar',
        currencySymbol: '\$',
        flag: '🇳🇦'),
    Country(
        name: 'Nauru',
        code: 'NR',
        dialCode: '+674',
        currency: 'Australian Dollar',
        currencySymbol: '\$',
        flag: '🇳🇷'),
    Country(
        name: 'Nepal',
        code: 'NP',
        dialCode: '+977',
        currency: 'Nepalese Rupee',
        currencySymbol: '₨',
        flag: '🇳🇵'),
    Country(
        name: 'Netherlands',
        code: 'NL',
        dialCode: '+31',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇳🇱'),
    Country(
        name: 'New Zealand',
        code: 'NZ',
        dialCode: '+64',
        currency: 'New Zealand Dollar',
        currencySymbol: '\$',
        flag: '🇳🇿'),
    Country(
        name: 'Nicaragua',
        code: 'NI',
        dialCode: '+505',
        currency: 'Nicaraguan Córdoba',
        currencySymbol: 'C\$',
        flag: '🇳🇮'),
    Country(
        name: 'Niger',
        code: 'NE',
        dialCode: '+227',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇳🇪'),
    Country(
        name: 'Nigeria',
        code: 'NG',
        dialCode: '+234',
        currency: 'Nigerian Naira',
        currencySymbol: '₦',
        flag: '🇳🇬'),
    Country(
        name: 'North Macedonia',
        code: 'MK',
        dialCode: '+389',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇲🇰'),
    Country(
        name: 'Norway',
        code: 'NO',
        dialCode: '+47',
        currency: 'Norwegian Krone',
        currencySymbol: 'kr',
        flag: '🇳🇴'),
    Country(
        name: 'Oman',
        code: 'OM',
        dialCode: '+968',
        currency: 'Omani Rial',
        currencySymbol: 'ر.ع.',
        flag: '🇴🇲'),
    Country(
        name: 'Pakistan',
        code: 'PK',
        dialCode: '+92',
        currency: 'Pakistani Rupee',
        currencySymbol: '₨',
        flag: '🇵🇰'),
    Country(
        name: 'Palau',
        code: 'PW',
        dialCode: '+680',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇵🇼'),
    Country(
        name: 'Palestine, State of',
        code: 'PS',
        dialCode: '+970',
        currency: 'Israeli New Shekel',
        currencySymbol: '₪',
        flag: '🇵🇸'),
    Country(
        name: 'Panama',
        code: 'PA',
        dialCode: '+507',
        currency: 'Panamanian Balboa',
        currencySymbol: 'B/.',
        flag: '🇵🇦'),
    Country(
        name: 'Papua New Guinea',
        code: 'PG',
        dialCode: '+675',
        currency: 'Papua New Guinean Kina',
        currencySymbol: 'K',
        flag: '🇵🇬'),
    Country(
        name: 'Paraguay',
        code: 'PY',
        dialCode: '+595',
        currency: 'Paraguayan Guarani',
        currencySymbol: '₲',
        flag: '🇵🇾'),
    Country(
        name: 'Peru',
        code: 'PE',
        dialCode: '+51',
        currency: 'Peruvian Nuevo Sol',
        currencySymbol: 'S/.',
        flag: '🇵🇪'),
    Country(
        name: 'Philippines',
        code: 'PH',
        dialCode: '+63',
        currency: 'Philippine Peso',
        currencySymbol: '₱',
        flag: '🇵🇭'),
    Country(
        name: 'Poland',
        code: 'PL',
        dialCode: '+48',
        currency: 'Polish Złoty',
        currencySymbol: 'zł',
        flag: '🇵🇱'),
    Country(
        name: 'Portugal',
        code: 'PT',
        dialCode: '+351',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇵🇹'),
    Country(
        name: 'Qatar',
        code: 'QA',
        dialCode: '+974',
        currency: 'Qatari Riyal',
        currencySymbol: 'ر.ق',
        flag: '🇶🇦'),
    Country(
        name: 'Republic of Kosovo',
        code: 'XK',
        dialCode: '+383',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇽🇰'),
    Country(
        name: 'Romania',
        code: 'RO',
        dialCode: '+40',
        currency: 'Romanian Leu',
        currencySymbol: 'lei',
        flag: '🇷🇴'),
    Country(
        name: 'Russia',
        code: 'RU',
        dialCode: '+7',
        currency: 'Russian Ruble',
        currencySymbol: '₽',
        flag: '🇷🇺'),
    Country(
        name: 'Rwanda',
        code: 'RW',
        dialCode: '+250',
        currency: 'Rwandan Franc',
        currencySymbol: 'Fr',
        flag: '🇷🇼'),
    Country(
        name: 'Saint Kitts and Nevis',
        code: 'KN',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇰🇳'),
    Country(
        name: 'Saint Lucia',
        code: 'LC',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇱🇨'),
    Country(
        name: 'Saint Vincent and the Grenadines',
        code: 'VC',
        dialCode: '+1',
        currency: 'East Caribbean Dollar',
        currencySymbol: '\$',
        flag: '🇻🇨'),
    Country(
        name: 'Samoa',
        code: 'WS',
        dialCode: '+685',
        currency: 'Samoan Tālā',
        currencySymbol: 'T',
        flag: '🇼🇸'),
    Country(
        name: 'San Marino',
        code: 'SM',
        dialCode: '+378',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇸🇲'),
    Country(
        name: 'Sao Tome and Principe',
        code: 'ST',
        dialCode: '+239',
        currency: 'São Tomé and Príncipe Dobra',
        currencySymbol: 'Db',
        flag: '🇸🇹'),
    Country(
        name: 'Saudi Arabia',
        code: 'SA',
        dialCode: '+966',
        currency: 'Saudi Riyal',
        currencySymbol: 'ر.س',
        flag: '🇸🇦'),
    Country(
        name: 'Senegal',
        code: 'SN',
        dialCode: '+221',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇸🇳'),
    Country(
        name: 'Serbia',
        code: 'RS',
        dialCode: '+381',
        currency: 'Serbian Dinar',
        currencySymbol: 'дин.',
        flag: '🇷🇸'),
    Country(
        name: 'Seychelles',
        code: 'SC',
        dialCode: '+248',
        currency: 'Seychellois Rupee',
        currencySymbol: '₨',
        flag: '🇸🇨'),
    Country(
        name: 'Sierra Leone',
        code: 'SL',
        dialCode: '+232',
        currency: 'Sierra Leonean Leone',
        currencySymbol: 'Le',
        flag: '🇸🇱'),
    Country(
        name: 'Singapore',
        code: 'SG',
        dialCode: '+65',
        currency: 'Singapore Dollar',
        currencySymbol: '\$',
        flag: '🇸🇬'),
    Country(
        name: 'Slovakia',
        code: 'SK',
        dialCode: '+421',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇸🇰'),
    Country(
        name: 'Slovenia',
        code: 'SI',
        dialCode: '+386',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇸🇮'),
    Country(
        name: 'Solomon Islands',
        code: 'SB',
        dialCode: '+677',
        currency: 'Solomon Islands Dollar',
        currencySymbol: '\$',
        flag: '🇸🇧'),
    Country(
        name: 'Somalia',
        code: 'SO',
        dialCode: '+252',
        currency: 'Somali Shilling',
        currencySymbol: 'Sh',
        flag: '🇸🇴'),
    Country(
        name: 'South Africa',
        code: 'ZA',
        dialCode: '+27',
        currency: 'South African Rand',
        currencySymbol: 'R',
        flag: '🇿🇦'),
    Country(
        name: 'South Sudan',
        code: 'SS',
        dialCode: '+211',
        currency: 'South Sudanese Pound',
        currencySymbol: '£',
        flag: '🇸🇸'),
    Country(
        name: 'Spain',
        code: 'ES',
        dialCode: '+34',
        currency: 'Euro',
        currencySymbol: '€',
        flag: '🇪🇸'),
    Country(
        name: 'Sri Lanka',
        code: 'LK',
        dialCode: '+94',
        currency: 'Sri Lankan Rupee',
        currencySymbol: 'Rs',
        flag: '🇱🇰'),
    Country(
        name: 'Sudan',
        code: 'SD',
        dialCode: '+249',
        currency: 'Sudanese Pound',
        currencySymbol: '£',
        flag: '🇸🇩'),
    Country(
        name: 'Suriname',
        code: 'SR',
        dialCode: '+597',
        currency: 'Surinamese Dollar',
        currencySymbol: '\$',
        flag: '🇸🇷'),
    Country(
        name: 'Sweden',
        code: 'SE',
        dialCode: '+46',
        currency: 'Swedish Krona',
        currencySymbol: 'kr',
        flag: '🇸🇪'),
    Country(
        name: 'Switzerland',
        code: 'CH',
        dialCode: '+41',
        currency: 'Swiss Franc',
        currencySymbol: 'CHF',
        flag: '🇨🇭'),
    Country(
        name: 'Syrian Arab Republic',
        code: 'SY',
        dialCode: '+963',
        currency: 'Syrian Pound',
        currencySymbol: '£S',
        flag: '🇸🇾'),
    Country(
        name: 'Taiwan',
        code: 'TW',
        dialCode: '+886',
        currency: 'New Taiwan Dollar',
        currencySymbol: 'NT\$',
        flag: '🇹🇼'),
    Country(
        name: 'Tajikistan',
        code: 'TJ',
        dialCode: '+992',
        currency: 'Tajikistani Somoni',
        currencySymbol: 'ЅМ',
        flag: '🇹🇯'),
    Country(
        name: 'Tanzania',
        code: 'TZ',
        dialCode: '+255',
        currency: 'Tanzanian Shilling',
        currencySymbol: 'Sh',
        flag: '🇹🇿'),
    Country(
        name: 'Thailand',
        code: 'TH',
        dialCode: '+66',
        currency: 'Thai Baht',
        currencySymbol: '฿',
        flag: '🇹🇭'),
    Country(
        name: 'Timor-Leste',
        code: 'TL',
        dialCode: '+670',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇹🇱'),
    Country(
        name: 'Togo',
        code: 'TG',
        dialCode: '+228',
        currency: 'West African CFA franc',
        currencySymbol: 'Fr',
        flag: '🇹🇬'),
    Country(
        name: 'Tonga',
        code: 'TO',
        dialCode: '+676',
        currency: 'Tongan Paʻanga',
        currencySymbol: 'T\$',
        flag: '🇹🇴'),
    Country(
        name: 'Trinidad and Tobago',
        code: 'TT',
        dialCode: '+1',
        currency: 'Trinidad and Tobago Dollar',
        currencySymbol: '\$',
        flag: '🇹🇹'),
    Country(
        name: 'Tunisia',
        code: 'TN',
        dialCode: '+216',
        currency: 'Tunisian Dinar',
        currencySymbol: 'د.ت',
        flag: '🇹🇳'),
    Country(
        name: 'Turkey',
        code: 'TR',
        dialCode: '+90',
        currency: 'Turkish Lira',
        currencySymbol: '₺',
        flag: '🇹🇷'),
    Country(
        name: 'Turkmenistan',
        code: 'TM',
        dialCode: '+993',
        currency: 'Turkmenistan Manat',
        currencySymbol: 'm',
        flag: '🇹🇲'),
    Country(
        name: 'Tuvalu',
        code: 'TV',
        dialCode: '+688',
        currency: 'Australian Dollar',
        currencySymbol: '\$',
        flag: '🇹🇻'),
    Country(
        name: 'Uganda',
        code: 'UG',
        dialCode: '+256',
        currency: 'Ugandan Shilling',
        currencySymbol: 'Sh',
        flag: '🇺🇬'),
    Country(
        name: 'Ukraine',
        code: 'UA',
        dialCode: '+380',
        currency: 'Ukrainian Hryvnia',
        currencySymbol: '₴',
        flag: '🇺🇦'),
    Country(
        name: 'United Arab Emirates',
        code: 'AE',
        dialCode: '+971',
        currency: 'United Arab Emirates Dirham',
        currencySymbol: 'د.إ',
        flag: '🇦🇪'),
    Country(
        name: 'United Kingdom',
        code: 'GB',
        dialCode: '+44',
        currency: 'British Pound Sterling',
        currencySymbol: '£',
        flag: '🇬🇧'),
    Country(
        name: 'United States of America',
        code: 'US',
        dialCode: '+1',
        currency: 'United States Dollar',
        currencySymbol: '\$',
        flag: '🇺🇸'),
    Country(
        name: 'Uruguay',
        code: 'UY',
        dialCode: '+598',
        currency: 'Uruguayan Peso',
        currencySymbol: '\$',
        flag: '🇺🇾'),
    Country(
        name: 'Uzbekistan',
        code: 'UZ',
        dialCode: '+998',
        currency: 'Uzbekistani Som',
        currencySymbol: 'лв',
        flag: '🇺🇿'),
    Country(
        name: 'Vanuatu',
        code: 'VU',
        dialCode: '+678',
        currency: 'Vanuatu Vatu',
        currencySymbol: 'VT',
        flag: '🇻🇺'),
    Country(
        name: 'Venezuela',
        code: 'VE',
        dialCode: '+58',
        currency: 'Venezuelan Bolívar',
        currencySymbol: 'Bs',
        flag: '🇻🇪'),
    Country(
        name: 'Vietnam',
        code: 'VN',
        dialCode: '+84',
        currency: 'Vietnamese Dong',
        currencySymbol: '₫',
        flag: '🇻🇳'),
    Country(
        name: 'Yemen',
        code: 'YE',
        dialCode: '+967',
        currency: 'Yemeni Rial',
        currencySymbol: '﷼',
        flag: '🇾🇪'),
    Country(
        name: 'Zambia',
        code: 'ZM',
        dialCode: '+260',
        currency: 'Zambian Kwacha',
        currencySymbol: 'ZK',
        flag: '🇿🇲'),
    Country(
        name: 'Zimbabwe',
        code: 'ZW',
        dialCode: '+263',
        currency: 'Zimbabwean Dollar',
        currencySymbol: '\$',
        flag: '🇿🇼')
  ];
  List<Country> countriesToShow = [];

  @override
  void initState() {
    countriesToShow = countries;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColorConstants.backgroundColor,
      body: Column(
        children: [
          const SizedBox(
            height: 20,
          ),
          WKSearchBarType4(
              cornerRadius: 15,
              onSearchChanged: (value) {
                setState(() {
                  if (value.isEmpty) {
                    countriesToShow = countries;
                  } else {
                    countriesToShow = countries
                        .where((element) =>
                            element.name
                                .toLowerCase()
                                .contains(value.toLowerCase()) ||
                            element.code
                                .toLowerCase()
                                .contains(value.toLowerCase()) ||
                            element.dialCode
                                .toLowerCase()
                                .contains(value.toLowerCase()))
                        .toList();
                  }
                });
              },
              onSearchCompleted: (value) {}),
          Expanded(
            child: ListView.separated(
              padding: const EdgeInsets.only(top: 20, bottom: 100),
              itemCount: countriesToShow.length,
              itemBuilder: (context, index) {
                final country = countriesToShow[index];
                return SizedBox(
                  height: 50,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(country.flag,
                              style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: AppColorConstants.mainTextColor,
                                  fontSize: 24)),
                          const SizedBox(
                            width: 20,
                          ),
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(country.code,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color:
                                          AppColorConstants.mainTextColor,
                                      fontSize: 18)),
                              Text(country.currency,
                                  style: TextStyle(
                                      color: AppColorConstants
                                          .subHeadingTextColor,
                                      fontWeight: FontWeight.w200,
                                      fontSize: 16))
                            ],
                          ),
                        ],
                      ),
                      Text(country.currencySymbol,
                          style: TextStyle(
                              fontWeight: FontWeight.w600,
                              color: AppColorConstants.mainTextColor,
                              fontSize: 18)),
                    ],
                  ),
                ).ripple(() {
                  widget.onSelect(country);
                  Get.back(closeOverlays: true);
                });
              },
              separatorBuilder: (ctx, index) {
                return divider(height: 0.2).vP16;
              },
            ),
          ),
        ],
      ).hp(DesignConstants.horizontalPadding),
    );
  }
}
